---
project_name: pwcli

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm
    targets:
      - linux_amd64
      - linux_arm
      - darwin_amd64
      - windows_amd64
    ldflags:
      - -s -w
      - -X {{ .ProjectName }}/cmd.Version={{.Version}}
      - -X {{ .ProjectName }}/cmd/.Commit={{.ShortCommit}}
      - -X {{ .ProjectName }}/cmd.Date={{ time "2006-01-02" }}
      - -X {{ .ProjectName }}/cmd.Name={{.ProjectName}}

changelog:
  use: git
  filters:
    exclude:
      - '^Merge branch'
  groups:
    - title: Features
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: 'Bug fixes'
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 1
    - title: 'Refactoring'
      regexp: "^.*refactor[(\\w)]*:+.*$"
      order: 2
    - title: Others
      order: 999

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

nfpms:
  - id: deb-packages
    # dont use {{ .ProjectName }} here :(
    package_name: pwcli
    file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    # builds:
    license: GPL-3
    bindir: /usr/bin
    vendor: Tommi2Day
    maintainer: "Tommi2Day <tommi2day@github.com>"
    description: |-
      Toolbox for validating, storing and query encrypted passwords
    formats:
      - deb
    # dependencies:
    provides:
      # dont use {{ .ProjectName }} here :(
      - pwcli

  - id: rpm-packages
    # dont use {{ .ProjectName }} here :(
    package_name: pwcli
    file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    # builds:
    maintainer: "Tommi2Day <tommi2day@github.com>"
    description: |-
      Toolbox for validating, storing and query encrypted passwords
    formats:
      - rpm
    # dependencies:
    provides:
      # dont use {{ .ProjectName }} here :(
      - pwcli
    # contents:

release:
  github:
    owner: tommi2day
    name: pwcli
  replace_existing_draft: true
  draft: true
  header: |
    ## PWCLI Release {{ .Tag }} ({{ time "2006-01-02" }})
  target_commitish: '{{ .Commit }}'
