package cmd

const (
	flagAlias        = "--alias"
	flagApp          = "--app"
	flagConfig       = "--config"
	flagCrypto       = "--crypto"
	flagDatadir      = "--datadir"
	flagDebug        = "--debug"
	flagIdentityDir  = "--identity-dir"
	flagInfo         = "--info"
	flagKeyFile      = "--key-file"
	flagKeydir       = "--keydir"
	flagKeypass      = "--keypass"
	flagKmsEndpoint  = "--kms_endpoint"
	flagKmsKeyID     = "--kms_keyid"
	flagLdapBase     = "--ldap.base"
	flagLdapBindDN   = "--ldap.binddn"
	flagLdapBindPass = "--ldap.bindpassword" //nolint:gosec
	flagLdapHost     = "--ldap.host"
	flagLdapInsecure = "--ldap.insecure"
	flagLdapPort     = "--ldap.port"
	flagLdapTargetDN = "--ldap.targetdn"
	flagLdapTLS      = "--ldap.tls"
	flagLogical      = "--logical"
	flagLogicalFalse = "--logical=false"
	flagMethod       = "--method"
	flagMount        = "--mount"
	flagPassword     = "--password"
	flagPath         = "--path"
	flagPlaintext    = "--plaintext"
	flagProfile      = "--profile"
	flagProfileset   = "--profileset"
	flagStoreDir     = "--store-dir"
	flagSystem       = "--system"
	flagTest         = "--test"
	flagType         = "--type"
	flagUnitTest     = "--unit-test"
	flagUser         = "--user"
	flagUsername     = "--username"
	flagVaultAddr    = "--vault_addr"
	flagVaultToken   = "--vault_token"

	cmdCreate   = "create"
	boolTrue    = "true"
	noRestart   = "no"
	secretMount = "secret"
	testID      = "test"
)
